platform:
  - x64
  - x86

configuration:
  - Release

install:
  - cmd: git clone https://github.com/ogrisel/python-appveyor-demo
  - ps: python-appveyor-demo\appveyor\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip instal nose numpy scipy"

build:
  project: windows\xgboost.sln
